name: Daily Check In
on:
  schedule:
    - cron: '0,30 0,5,11 * * *'
    # UTC时间，分别对应了北京时间的8点、13点、19点的整点和30分

jobs:
  sign_in:
    runs-on: ubuntu-latest
    # 定义系统类型，这里选择Ubuntu
    steps:
    - name: '[Prepare] Code Check'
      uses: actions/checkout@v2
      # 从该仓库clone代码到虚拟机
    - name: '[Prepare] Set python'
      uses: actions/setup-python@v1
      # 安装python
      with:
        python-version: '3.x'
    - name: '[Prepare] Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade requests
        # 安装需要的python库
    - name: '[Final Main] Check In'
      run: |
        python submit.py
        # 执行代码
